version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/atletasimple?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - minha-rede

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: atletasimple
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - minha-rede

networks:
  minha-rede:
